theme: minima
<!-- 
title: Data Analyst Portfolio
author: Hope Mumbi Makanga 
description: A curated collection of my data analysis projects, dashboards and visualizations.  Explore my work in Excel, PowerBI, R, Python, and SQL where I transform data into actionable insights and stories.
-->
